services:
    object-tracker:
        image: object-tracker-image:1
        build:
            context: .
        container_name: object-tracker-cont
        volumes:
            - ./data:/app/data
        tty: true

        # If GPU acceleration is available:
        # deploy:
        #     resources:
        #         reservations:
        #             devices:
        #                 - driver: nvidia
        #                   count: all
        #                   capabilities: [gpu]
